Improve session pod labels
eclipse-theia/theia-cloud pull request #362
Opened 2024-10-22 22:30 UTC by xai

org.eclipse.theia.cloud.common.util.LabelsUtil is added to encapsulate creation of labels.

To indicate that a pod is a user session, its
'app.kubernetes.io/component' label is set to 'session'.

For custom labels, we use the prefix 'theia-cloud.io'.

This is currently used for:
- Identifying a session pods associated with a user: 'theia-cloud.io/user' = '$username'
- Identifying a session pod by appdefinition name: 'theia-cloud.io/app-definition' = $appdefinitionname

2024-10-23 12:47 UTC, lucas-koehler requested changes
Hi @xai ,
Thanks for this improvement :) Generally the changes look pretty good to me already. I have  a few small remarks inline. Please have a look :)

2024-10-23 12:47 UTC, lucas-koehler commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/util/LabelsUtil.java
> +    }
While we already add the `app.kubernetes.io/component` annotation, I think we should also add the `app.kubernetes.io/part-of` annotation with value `theia-cloud`.
This is helpful if Theia Cloud is installed together with other services in the same namespace. When we eventually apply this to all of Theia Cloud's components, this provides a selector to get everything related to Theia Cloud.

What do you think?

2024-10-23 12:47 UTC, lucas-koehler commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/util/LabelsUtil.java
> +        String userName = sessionSpec.getUser().split("@")[0];
Is there a reason we remove the second part of the email address (in case the user is an email address)? I would not do this because in deployments with a larger user base this can lead to collisions quite easily.

2024-10-23 12:47 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/session/EagerStartSessionHandler.java
> +                    LOGGER.info("Setting pod labels");
I think this should only be a debug level log as nothing exiting or too relevant happens here functionality wise.

```suggestion
                    LOGGER.debug("Setting service labels");
```

2024-10-23 12:47 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/session/LazySessionHandler.java
> +                    LOGGER.info("Setting pod labels");
I think this should only be a debug level log as nothing exiting or too relevant happens here functionality wise.
```suggestion
                    LOGGER.debug("Setting pod labels");
```

2024-10-23 14:22 UTC, lucas-koehler commented
> In the long run, I think we should consider adding the same labels to all deployments, services, and configmaps that are created. 

I agree: Eventually we should label _all_ components created by Theia Cloud, either by the operator or the Helm charts.

> I think we may also ignore the EagerStartSessionHandler for now.
I am not sure if we should remove this handler for 1.0.0, since it does not cover all functionality anyway.

I think we should leave it in but make very clear in the documentation on the website, the helm charts and potentially here that the implementation is not up to par. My reason for leaving it in is that it might encourage contributions to improve this and shows our intent on bringing this up to par eventually. Furthermore, it allows basic prototyping of eager start. WDYT?

2024-10-24 07:16 UTC, jfaltermeier commented
> I think we should leave it in but make very clear in the documentation on the website, the helm charts and potentially here that the implementation is not up to par. My reason for leaving it in is that it might encourage contributions to improve this and shows our intent on bringing this up to par eventually. Furthermore, it allows basic prototyping of eager start. WDYT?

Sounds good

2024-11-20 08:40 UTC, xai commented on java/common/org.eclipse.theia.cloud.common/src/main/java/org/eclipse/theia/cloud/common/util/LabelsUtil.java
> +        String userName = sessionSpec.getUser().split("@")[0];
I adjusted that to use the full email address. I had to translate the `@` because labels must not contain that character.

2024-11-21 08:36 UTC, jfaltermeier approved these changes
LGTM

2024-11-21 09:03 UTC, lucas-koehler approved these changes
Code changes LGTM me. I have one very minor, non-blocking suggestion inline.
I did not retest the second iteration though. @jfaltermeier Did you test it? Otherwise, I can still do it.

2024-11-21 09:03 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/util/K8sUtil.java
> +                Deployment deployment = (Deployment) newItem;
Minor: As we use Java 17, you should be able to simplify this:
```suggestion
            if (newItem instanceof Deployment deployment) {
```

2024-11-21 10:08 UTC, jfaltermeier commented
> Code changes LGTM me. I have one very minor, non-blocking suggestion inline. I did not retest the second iteration though. @jfaltermeier Did you test it? Otherwise, I can still do it.

I did a short test and saw the labels on pods, deployments, services, and config maps

2024-11-28 07:50 UTC, merged