WIP Document naming conventions & Naming alignment
eclipse-theia/theia-cloud pull request #368
Opened 2024-10-29 12:14 UTC by jfaltermeier

Contributed on behalf of STMicroelectronics

2024-10-29 13:34 UTC, sgraband commented on documentation/Naming.md
> +- **File names**
```suggestion
- **File names**
- **k8s namespaces**
```

2024-10-29 13:42 UTC, lucas-koehler requested changes
Hi @jfaltermeier, thanks for aligning the naming and the documentation. This saves a lot of wondering what is the correct spelling :sparkles: 

The changes already look pretty good to me. I have two remarks inline. One tiny suggestion and one hint regarding consistency in Kubernetes label key naming. Please have a look.

2024-10-29 13:42 UTC, lucas-koehler commented on documentation/Naming.md
> +In general documentation and free text, use the standard project name, **Theia Cloud** (with a space). Avoid spaces in technical contexts.
```suggestion
In general documentation and free text, use the standard project name **Theia Cloud** (with a space). Avoid spaces in technical contexts.
```

2024-10-29 13:42 UTC, lucas-koehler commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/appdef/EagerStartAppDefinitionAddedHandler.java
> +    public static final String LABEL_KEY = "theia-cloud.io/template-purpose";
We should be consistent with word separators also after the prefix.
Here we use a dash in `template-purpose`.
However, in other places we use a label like `theia-cloud.io/workspace.name: placeholder-label-workspace-name`.

We should use either dot or dash consistently. I slightly prefer dashes as they seem more typical in a uri resp. dns name format to me. WDYT?

2024-10-29 13:59 UTC, jfaltermeier commented on node/monitor/package.json
> +  "name": "theia-cloud-monitor",
The npm package is already published under a name following the conventions: https://www.npmjs.com/package/@eclipse-theiacloud/monitor-theia. 
This one here is the vsix, which hasn’t been published to open-vsx yet, so we should be fine.

2024-10-29 14:00 UTC, jfaltermeier commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/appdef/EagerStartAppDefinitionAddedHandler.java
> +    public static final String LABEL_KEY = "theia-cloud.io/template-purpose";
Sounds good, I will adjust this

2024-10-29 20:08 UTC, jfaltermeier commented
We have to use `THEIACLOUD` for env variables, because Theia messes with variables starting with `THEIA_`

I addressed this + the comments above now

2024-10-29 20:10 UTC, jfaltermeier commented on java/operator/org.eclipse.theia.cloud.operator/src/main/java/org/eclipse/theia/cloud/operator/handler/appdef/EagerStartAppDefinitionAddedHandler.java
> +    public static final String LABEL_KEY = "theia-cloud.io/template-purpose";
I updated `theia-cloud.io/workspace.name` to `theia-cloud.io/workspace-name`

2024-10-29 20:13 UTC, jfaltermeier commented
This is the theia code: https://github.com/eclipse-theia/theia/blob/f29c3d04241b32791462c7027938abeb887f8140/packages/core/src/node/messaging/ipc-protocol.ts#L67

2024-10-30 09:23 UTC, lucas-koehler approved these changes
Thanks for the updates. LGTM now :sparkles:

2024-10-30 09:31 UTC, merged